# Generated by Django 3.2.3 on 2022-02-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('available_stock', models.IntegerField()),
                ('delivery', models.BooleanField()),
                ('delivery_radius', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(upload_to='')),
                ('image_3', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
